// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLs5UH-Gu-dEpNyFltZh71W-9Wq3ChrGY',
    appId: '1:11917914593:web:23884a3c989ea42116a2a0',
    messagingSenderId: '11917914593',
    projectId: 'kaliop-tournament',
    authDomain: 'kaliop-tournament.firebaseapp.com',
    databaseURL: 'https://kaliop-tournament-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kaliop-tournament.firebasestorage.app',
    measurementId: 'G-D9J0H9WPFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvbtyN6UqRsS0HKh9I-BPl2HcRUXgymKY',
    appId: '1:11917914593:android:e1569ba3893e81a016a2a0',
    messagingSenderId: '11917914593',
    projectId: 'kaliop-tournament',
    databaseURL: 'https://kaliop-tournament-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kaliop-tournament.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqX-nvrLtyEycmGnnJo4VzZ3DpFu4ted8',
    appId: '1:11917914593:ios:4f76db6d45fb085d16a2a0',
    messagingSenderId: '11917914593',
    projectId: 'kaliop-tournament',
    databaseURL: 'https://kaliop-tournament-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kaliop-tournament.firebasestorage.app',
    iosBundleId: 'com.example.tournamentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqX-nvrLtyEycmGnnJo4VzZ3DpFu4ted8',
    appId: '1:11917914593:ios:4f76db6d45fb085d16a2a0',
    messagingSenderId: '11917914593',
    projectId: 'kaliop-tournament',
    databaseURL: 'https://kaliop-tournament-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kaliop-tournament.firebasestorage.app',
    iosBundleId: 'com.example.tournamentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLs5UH-Gu-dEpNyFltZh71W-9Wq3ChrGY',
    appId: '1:11917914593:web:a037a6ec9578c02516a2a0',
    messagingSenderId: '11917914593',
    projectId: 'kaliop-tournament',
    authDomain: 'kaliop-tournament.firebaseapp.com',
    databaseURL: 'https://kaliop-tournament-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kaliop-tournament.firebasestorage.app',
    measurementId: 'G-PND17FRYM2',
  );
}
